### ISSUE TITLE
Get r property from object

### ISSUE THREAD

**Issue by jjzcru** [mwielbut/sails-hook-thinky#2]
I got his object

```
Incomes.orderBy({index: r.desc("createdAt")}).run(function(err, created){
            if (err){
                deferred.reject(new Error(err));
            }
            else{
                deferred.resolve(created);
            }
        });
```

How do get the r property to make the sort?

**Comment by mwielbut** [comment]
You should be able to get 'r' from the global 'thinky'
var p = Post.orderBy({index: thinky.r.desc("createdAt")}).run()
Sorry, going from memory here - spotty Internet and no laptop.
